<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/pais.css">
    <title>Pais</title>
</head>
<body>
    <div class="form form-pais">
    <div class="caja"><img src="img/pais.jpg" class="pais"></div>
      <h1>País</h1>
        <label for="pais" class="label label-pais">Nombre del país:</label>
        <input type="text" id="pais" name="pais" class="input">
    </div>
</body>
</html>