<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/publicacion.css">
    <title>Document</title>
</head>
<body>
<div class="form form-comentario">

    <div class="caja"><img src="img/publicacion.jpg" class="comentario"></div>
      <h1>publicacion</h1>
    <div class="id">
    <span class="label lavel-id">
    <label for="id" class="id">Seleccione su ID:</label>
    </span > 
    <span class="select-id">
        <select name="id" id="id" autofocus>
          <option value="volvo">1</option>
          <option value="saab">2</option>
          <option value="opel">3</option>
          <option value="audi">4</option>
        </select>
    </span>
    </div>
    <div class="id">
    <span class="label lavel-id">
    <label for="id" class="id">Seleccione el ID del usuario:</label>
    </span > 
    <span class="select-id">
        <select name="id" id="id" autofocus>
          <option value="volvo">1</option>
          <option value="saab">2</option>
          <option value="opel">3</option>
          <option value="audi">4</option>
        </select>
    </span>
    </div>
    <div class="text">
    <label for="w3review" class="label label-comentario">Escriba aqui su publicacion:</label>
    <textarea id="w3review" name="w3review" rows="4" cols="50"></textarea>
    </div>
    <div class="label label-fecha">
    <label for="fnacimiento">Fecha Nacimiento:</label>
    <input type="date" id="fnacimiento" name="fnacimiento" class="input">
    </div>
    </div>
</body>
</html>