<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/tiporeaccion.css">
    <title>Document</title>
</head>
<body>
<div class="form">
    <div class="caja"><img src="img/login.jpg" class="login"></div>
      <h1>Registro</h1>
      <form action="/registro" method="post">
    <div class="id espacio">
    <span class="label lavel-id">
    <label for="id" class="id">Seleccione su ID:</label>
    </span > 
    <span class="select-id">
        <select name="id" id="id" autofocus>
          <option value="volvo">1</option>
          <option value="saab">2</option>
          <option value="opel">3</option>
          <option value="audi">4</option>
        </select>
    </span>
    </div>
        <div class="espacio">
        <label for="name">Tipo de cara:</label>
        <input type="text" id="name" name="name" class="input">
        </div>
        <div>
        <label for="name" class="label">imagen:</label>
        <input type="text" id="name" name="name" class="input-imagen">
        </div>
    </div>
    
</body>
</html>