<!DOCTYPE html>
<html>

<head>
  <title>Listado de Usuarios</title>
  <link rel="stylesheet" href="/css/main.css">
</head>

<body>
  <div class="container">
    <h1>Listado Reacciones</h1>
    <table>
      <tr>
        <th>Id</th>
        <th>Accion</th>
        <th>imagen</th>
      </tr>
      <?php foreach($tipoReacciones as $tipoReaccion): ?>
      <tr>
        <td><?=$tipoReaccion->getId()?></td>
        <td><?=$tipoReaccion->getTipoCara()?></td>
        <td><?=$tipoReaccion->getImagen()?></td>
        <td>
          <a href="/tiporeaccion/<?=$tipoReaccion->getId()?>/edit"><button>Editar</button></a>
          <a href="/tiporeaccion/<?=$tipoReaccion->getId()?>/delete"><button>Eliminar</button></a>
        </td>
      </tr>
      <?php endforeach; ?>
    </table>
    <a href="/tiporeaccion/create"><button>Crear</button></a>
  </div>
</body>