<!DOCTYPE html>
<html>

<head>
  <title>Registro</title>
  <link rel="stylesheet" href="/css/main.css">
</head>

<body>
  <div class="form register-form">
    <h1><?= $publicacion ? "Editar" : "Crear" ?> Publicacion <?= $publicacion ? $publicacion->getIdUsuario(): "" ?></h1>
    
    
    <form action="/publicacion/<?= $publicacion ? $publicacion->getId() . "/edit":"create" ?>" method="post">
   
    <label for="idUsuario" class="nacionalidad">seleccion de usuario:</label>
      <select name="idUsuario" id="nacionalidad" autofocus>
        <?php foreach($usuarios as $usuario ): ?>
        <option value="<?=$usuario->getId()?>"><?=$usuario->getNombre()?></option>
        <?php endforeach; ?>
      </select>
      <br><br>

      <label for="date">Fecha: </label>
      <input type="datetime-local" name="date" value="<?= $publicacion ? $publicacion->getDate() : "" ?>">
      <br>
      <label for="texto">Mensaje: </label>
      <input type="text" name="texto" value="<?= $publicacion ? $publicacion->getTexto() : "" ?>">
      <br>
      
      <input type="submit" value="Guardar">
    </form>
  </div>
</body>